import { noPrefix } from "./Graph/Tree/Trie/good set bad set";
// import { runningMedian } from "./2 heaps running median";

// const a = [12, 4, 5, 3, 8, 7];

// const b = runningMedian(a);

// console.info(b);

// deepStrictEqual([12.0,
// 	8.0,
// 	5.0,
// 	4.5,
// 	5.0,
// 	6.0], b);
// console.info('runningMedian passed tests!')

const input = `efhhaihggd
afbgfaaiacbag
hggfaeddhfadadhiiibah
aggjjbechjbcd
efjefcaehadeiea
ihjieaejfei
edfgbfbjbahiacfjfccadjfe
fahjehhfadihbgjdhgajcaihgjade
ihchdhacbhcahhgaa
jbcdaddccfdef
ccdfecaedeahfaahfbcgdhchecggd
agahghheaejhhgeccigd
ebd
jidifefcafg
hbjacdghidfchhhhfdebfjbfgjafd
cgffgeicgegeagdhdigjjdbigdhbgi
jhcejcaihabgcgebff
beeheedjacieefdd
cbhhdbigbaecjaeabccaehdhghhjg
fai
jba
fddfachhhcgj
fbfahiacgibieicdcjcgbfd
biiabce
ihbibcdddbfigcdabbibc
gjh
abhbedhhhgchigbfa
fjgbdfdabajbbg
cdediifceejbgcjheda
figffgjjiadcaafac
ehfheifafhd
jficfjhheicfaiaehejeeddcehhie
bbd
hbfegffbbggbedfdiggef
feigjdheiggdedcjdb
chjbfcffibchcijefaibfbdc
dajbhagjagfahfeij
jcegcfje
hcjdgjdbdghhbfeeffgj
ddjjdb
iecbbidafjbe
fbbdbccbbjebdgbagc
fjejbgggbcbidfiihgaigjddee
ihbdfihbefjfbajghdhgdfdbgc
acjehdiidfajh
bifafjehdj
cjd
bhbabecbgea
bdfjghdg
ddajeebfafij
jahafjcfehbhe
ejjgbchfhjfaebgdbgf
cbcc
fgedjcijheeaiibdbdgjiidb
gdjhadbjbfabbafc
hhaidjgbfhfeefhf
dbcieehgajbjijijhcjhbeediccefg
cghdhcaceacebajgjcgahbejdfe
hdjecai
bjbdfcibdj
cci
gchhhebiji
djccgjhcfdejbgaihacehhiieaiai
gejbdbd
bjijcbeaehgbgicib
cbg
ijedchdbijebbcbehagdjde
jbfbeihbegcebidfbbbdbgihji
fhbfhchfbbbhb
ej
fgbjihghijifcebfajgh
eiccbdjhdfedbijciaj
gfaagchei
jjfhce
gbia
be
hbdce
ffajicjcdbjdfdibdfeajhej
bejdacjcddagbbjgjhcdhhdfahcie
gdfajhadaebbfhefgcbba
ideagcgacc
bibccggebch
bffihhfecehfdgaagacgbcgegjfhd
hjghdj
gbcechiiagefahegeigfgf
ieggbccda
hdf
ebhffddgiagfefhdgbbag
cihgffjhacfibihfgfda
fi
geiacbccjjhcbgbibfgbjaebihbcfg
acg
dfejgbbfdeefaaaagf
d
ebhgjbbadjidhfgjgjjhiidhbcab
adahgdafcabaidcfbffghf
fhjaheadc
iacbebheicgeeejdceagehhdbdbgda
cbbfbdj
ahheiiedhbgijfabe
jjijihibddfi
hdagcjaadegbjgadahaif
dhfdccggfecgijjggcjgjdhhaeicjf
habjddficfhhhhifgfifc
jccabbgbegjggaabciajbdjddc
icjgfbffcgegefbeaeecahibeeaib
jgdhbjaiijhdbfibggahbeedc
eggbafi
dgbiaaed
haeeehhfdfcgeagfgda
ejbbhjcaafjbiibjfggejhjd
faheag
jegjjeacfdg
afdbicbgd
hcbchafiadfejdajigfbae
gbbgeffhjaggbjicbj
acjceehcjfbadhgcfhjbbahhdifjd
abcaibbdbdbffjgg
cbhejbb
fahhbeihedabhfdffdigaeehaiehej
gjijfaifjbficfechicihhh
jhaihdfdeefbiaagfgddfh
gifehgijfgjgdjagfe
ajf
ihijibjdiehhhecabh
hdaciciggghc
bfddegfe
gdgjbaahbbgbbcefcddgjhj
jbdeaebaed
gdeaedcefaaifbcbdcbe
jhecdde
ffbjaejdgdgfbacaacffeejef
ggeciebagjgiajdaa
dgdggchjhf
hdffccf
adjgigcdf
hijffghjhghagbfdgecabiifjij
jjdfcijheih
ebfdddffcegged
bjbgbgdaegfedjfeihibhddh
igjehfheecfbjjfffjifibbj
cddhdcbjfddfbegbiagbfeaceaiccc
fadcbcffcfhhjaaffbhdceahbhbcdb
begfihhgdaiegaejgbbbacbf
jdjfa
agjfhjaahjghi
igjebfgjehbbbaia
dbfbcbhegaddjjcej
iec
fhjbichcjggiffjabgejidih
ejgghjccdfbadfhhfg
hfhe
befffagfhgfafagefjg
bcafahhccgdji
gh
gfhbgdgbhfgheiefdiag
igijheeijihggdjefecejgjjcefi
gdcihedcegfacagc
gejhfbbdee
fae
difjjggabheeijajjjcfd
cibbccj
ehb
djhjdjdfadgibeihjjcceaa
icefaacagaceeidjaf
eefiedh
gccdbcegidhcjjegdcbdg
bhjbbbjfcaddcibfbcgighehdb
ggfdhhggdeidghje
iadcebhbiecihbcgbbffehjjhhha
cccebabfbjcjgehbfbdcc
cdafhe
giie
bgfiadibj
dfefaccdfaeafjccgjb
ibdedaeeebdgbfahaaheacce
hej
dafhahc
jgecegbhfebfcdbbcggcigbabdgafa
hejhhhghheidddfhc
fbaifeiiaaibcfcgaff
cgddjdiifcggccggheda
fhfjbghfhibiiihgbbjejab
dcgdbjgeihcg
hcadcahgeijgb
afacaf
dahijfjbfe
gbgicbg
jhcecfcggeeg
acbhaffbjfdbaehgcjbcacbacj
igeeaabhiig
dhgdheagggjbdedhaihgje
dhegdhcibijeeaifdd
jbjbbi
d
fhiehcdgdhbfjcejfghgejf
jecga
dfdigfc
iifebdcief
cehfdhajgafjfea`

const words = input.split('\n');

noPrefix(words);